### ISSUE TITLE
Unable to load the requested class: Wildfire

### ISSUE THREAD

**Issue by blinkinglight** [rougin/combustor#18]
[mz@archlinux test_grc]$ composer require rougin/combustor --dev
Using version ^1.2 for rougin/combustor
./composer.json has been updated
Running composer update rougin/combustor
Loading composer repositories with package information
Updating dependencies
Lock file operations: 20 installs, 0 updates, 0 removals
  - Locking doctrine/inflector (1.4.3)
  - Locking league/flysystem (1.1.3)
  - Locking league/mime-type-detection (1.7.0)
  - Locking psr/container (1.0.0)
  - Locking psr/http-message (1.0.1)
  - Locking psr/log (1.1.3)
  - Locking rdlowrey/auryn (v1.4.3)
  - Locking rougin/blueprint (v0.6.0)
  - Locking rougin/combustor (v1.2.4)
  - Locking rougin/describe (v1.7.0)
  - Locking rougin/slytherin (v0.9.5)
  - Locking rougin/spark-plug (v0.4.4)
  - Locking rougin/wildfire (v0.3.1)
  - Locking symfony/console (v3.4.47)
  - Locking symfony/debug (v4.4.19)
  - Locking symfony/polyfill-ctype (v1.22.1)
  - Locking symfony/polyfill-mbstring (v1.22.1)
  - Locking symfony/polyfill-php80 (v1.22.1)
  - Locking symfony/yaml (v3.4.47)
  - Locking twig/twig (v1.44.2)
Writing lock file
Installing dependencies from lock file (including require-dev)
Package operations: 20 installs, 0 updates, 0 removals
  - Installing doctrine/inflector (1.4.3): Extracting archive
  - Installing league/mime-type-detection (1.7.0): Extracting archive
  - Installing league/flysystem (1.1.3): Extracting archive
  - Installing rdlowrey/auryn (v1.4.3): Extracting archive
  - Installing rougin/spark-plug (v0.4.4): Extracting archive
  - Installing rougin/describe (v1.7.0): Extracting archive
  - Installing symfony/polyfill-ctype (v1.22.1): Extracting archive
  - Installing twig/twig (v1.44.2): Extracting archive
  - Installing symfony/yaml (v3.4.47): Extracting archive
  - Installing symfony/polyfill-mbstring (v1.22.1): Extracting archive
  - Installing symfony/polyfill-php80 (v1.22.1): Extracting archive
  - Installing psr/log (1.1.3): Extracting archive
  - Installing symfony/debug (v4.4.19): Extracting archive
  - Installing symfony/console (v3.4.47): Extracting archive
  - Installing psr/http-message (1.0.1): Extracting archive
  - Installing psr/container (1.0.0): Extracting archive
  - Installing rougin/slytherin (v0.9.5): Extracting archive
  - Installing rougin/blueprint (v0.6.0): Extracting archive
  - Installing rougin/combustor (v1.2.4): Extracting archive
  - Installing rougin/wildfire (v0.3.1): Extracting archive
21 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating autoload files
10 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
[mz@archlinux test_grc]$ vendor/bin/combustor install:wildfire

ERROR: An Error Was Encountered

	Unable to load the requested class: Wildfire

[mz@archlinux test_grc]$ vendor/bin/combustor install:doctrine

ERROR: An Error Was Encountered

	Unable to load the requested class: Wildfire

[mz@archlinux test_grc]$

**Comment by rougin** [comment]
Hi @blinkinglight , apologies for the late reply in this issue. I was on hiatus when this issue was created.

In the next release of Combustor, I already implemented the usage of [rougin/wildfire](https://github.com/rougin/wildfire) instead of creating the said `Wildfire` class in the `libraries` directory.

You may checkout the `dev-master` branch first to fix this issue. Thanks!
