### ISSUE TITLE
Fatal error: Class 'Describe\Describe' not found

### ISSUE THREAD

**Issue by kenjis** [rougin/combustor#2]
combustor command does not work.

```
$ composer require rougin/combustor
$ php vendor/bin/combustor install:doctrine
$ vendor/bin/combustor create:scaffold test
```

> Fatal error: Class 'Describe\Describe' not found in .../CodeIgniter-3.0.0/vendor/rougin/combustor/src/Doctrine/CreateControllerCommand.php on line 58

**Comment by rougin** [comment]
Oh. I forgot to release a new version for it. It's already fixed in `dev-master`. For a workaround about that issue, just replace `use Describe\Describe` with `use Rougin\Describe\Describe` for now. Thanks!

EDIT: Already released a new version :+1:

**Comment by kenjis** [comment]
Thank you. This error is gone.
