### ISSUE TITLE
WAMP / windows

### ISSUE THREAD

**Issue by boblennes** [rougin/combustor#4]
I get no errors but nothing happens? Output below no matter what command I try.

E:\Program Files (x86)\EasyPHP-12.1\www\generate>php "vendor/bin/combustor" inst
all:wildfire
SRC_DIR="`pwd`"
cd "`dirname "$0"`"
cd "../rougin/combustor/bin"
BIN_TARGET="`pwd`/combustor"
cd "$SRC_DIR"
"$BIN_TARGET" "$@"

**Comment by boblennes** [comment]
Also tried:
php vendor\bin\combustor install:wildfire
vendor\bin\combustor create:scaffold --bootstrap customers

**Comment by rougin** [comment]
Hello! This issue is maybe caused with the symbolic links in Windows. Maybe you can try this:

`php vendor/rougin/combustor/bin/combustor`

**Comment by boblennes** [comment]
Tried:
php vendor/rougin/combustor/bin/combustor install:wildfire
php vendor/rougin/combustor/bin/combustor  create:scaffold --bootstrap customers

No output - is there a debugging or error log..?

**Comment by rougin** [comment]
Hmmm. Have you tried `php vendor/rougin/combustor/bin/combustor.php`? Can you check your current PHP version using the `php -v` command?

**Comment by boblennes** [comment]
.php did not work either...

PHP 5.5.12 (cli) (built: Apr 30 2014 11:20:55)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

**Comment by rougin** [comment]
That's very strange. This problem is also the same with these. https://github.com/robmorgan/phinx/issues/360#issuecomment-68865221. Is there a `combustor.bat` file located in `vendor/bin`? Can you try to access it?

**Comment by rougin** [comment]
Or maybe try using [this](https://git-scm.com/downloads) as the command line client.

**Comment by boblennes** [comment]
Tried both - no luck. There is a .bat but all it does is set BIN_TARGET before running.

**Comment by rougin** [comment]
Hmmm. I tried to install EasyPHP on my Windows machine and use it with no errors. How did you install Composer in your system? Did you use the installer provided by Composer? Maybe try this [one](https://github.com/composer/composer/issues/2851). If anything else fails, delete the `vendor` folder and `composer.lock` then install it again using `composer install`.
